name: Deploy Spring Boot JAR to EC2

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Upload JAR to EC2 via SCP
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        source: "target/myDockerApp-0.0.1-SNAPSHOT.jar"
        target: "~/app.jar"

    - name: Run Spring Boot JAR on EC2 via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          pkill -f 'java -jar' || true
          nohup java -jar app.jar \
            --DB_HOST=${{ secrets.DB_HOST }} \
            --DB_USER=${{ secrets.DB_USER }} \
            --DB_PASS=${{ secrets.DB_PASS }} \
            --JWT_SECRET=${{ secrets.JWT_SECRET }} \
            > output.log 2>&1 &
